fix: add missing Slack API method to send failure notification
This commit fixes an error when a workflow fails and tries to notify
Slack:

> SlackError: Missing input! A method must be decided to use the token
  provided.

See: https://github.com/slackapi/slack-github-action?tab=readme-ov-file#technique-2-slack-api-method